### ISSUE TITLE
usemin option doesn't work

### ISSUE THREAD

**Issue by Hotell** [ericclemmons/grunt-angular-templates#70]
Hi, 
trying to append templates to final script file via usemin option but it doesn't work:

(I'm using Yeoman)

Here is **HTML snippet**

```html
        <!-- build:js({.tmp,app}) scripts/scripts.js -->
        <script src="scripts/app.js"></script>
        <script src="scripts/controllers/main.js"></script>
        <!-- endbuild -->
```

**Gruntfile:**

```js
  // compiles templates to cache
      ngtemplates: {
          dist: {
              options: {
                  module: 'testApp',
                  usemin: 'scripts/scripts.js'
              },
              cwd: '<%= yeoman.app %>',
              src: 'views/**/*.html',
              dest: '<%= yeoman.app %>/scripts/templates.js'
          }
      }
...
...
// build task
grunt.registerTask('build', [
    'clean:dist',
    'bower-install',
    'useminPrepare',
    'ngtemplates',
    'concurrent:dist',
    'autoprefixer',
    'concat',
    'ngmin',
    'copy:dist',
    'cdnify',
    'cssmin',
    'uglify',
    'rev',
    'usemin',
    'htmlmin'
  ]);
```

when running task:

```bash 
$ grunt build
```

grunt throws this error:
```bash
Running "ngtemplates:dist" (ngtemplates) task
File dist/scripts/templates.js created.
>> Could not find usemin.generated path matching: scripts/scripts.js
````

**Comment by niyando** [comment]
totally unrelated,
@Hotell whats your workflow when you serve app locally?

**Comment by underscorebrody** [comment]
Closing this, I think it is resolved

**Comment by kadosh1000** [comment]
Having the same issue on windows machine, changing to double backslash didn't fix it either
